name: pupdoc
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  animate_gradient: ^0.0.3
  material_design_icons_flutter: ^7.0.7296
  linear_progress_bar: ^1.1.3
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  flutter_dotenv: ^5.2.1
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - "lib/assets/png/pupdoclogologin.png"
    - "lib/assets/png/pupdoclogoregister.png"

  fonts:
    - family: SansationRegular
      fonts:
        - asset: lib/assets/font/sansation/Sansation-Regular.ttf
    - family: SansationBold
      fonts:
        - asset: lib/assets/font/sansation/Sansation-Bold.ttf
