name: pupdoc
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animate_gradient: ^0.0.3
  material_design_icons_flutter: ^7.0.7296
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  flutter_dotenv: ^5.2.1
  email_validator: ^3.0.0
  rive: ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - "lib/assets/png/pupdoclogologin.png"
    - "lib/assets/png/pupdoclogoregister.png"
    - "lib/assets/riveAssets/"
    - "lib/assets/png/background/stateBackground/"
    - "lib/assets/png/background/accountBackground/"
    - "lib/assets/png/iconsAccount/"
    - "lib/assets/png/iconsPet/"
    - "lib/assets/png/background/forumBackground/"

  fonts:
    - family: SansationRegular
      fonts:
        - asset: lib/assets/font/sansation/Sansation-Regular.ttf
    - family: SansationBold
      fonts:
        - asset: lib/assets/font/sansation/Sansation-Bold.ttf

