// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC67vvRKwO4-5RpO9p2N6iyfNGEIabzxSw',
    appId: '1:294641802180:web:f8509c20020ab888ba2291',
    messagingSenderId: '294641802180',
    projectId: 'pupdoc',
    authDomain: 'pupdoc.firebaseapp.com',
    storageBucket: 'pupdoc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAemfyrzqnhKgNPNQv3Q2SVC3wrJaIP5Rk',
    appId: '1:294641802180:android:e50c3450ab760313ba2291',
    messagingSenderId: '294641802180',
    projectId: 'pupdoc',
    storageBucket: 'pupdoc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADt1_IeTy6iwA4i9cobdhXzMLFlEuClCw',
    appId: '1:294641802180:ios:c8a9252729c2ce5fba2291',
    messagingSenderId: '294641802180',
    projectId: 'pupdoc',
    storageBucket: 'pupdoc.firebasestorage.app',
    iosBundleId: 'com.example.pupdoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADt1_IeTy6iwA4i9cobdhXzMLFlEuClCw',
    appId: '1:294641802180:ios:c8a9252729c2ce5fba2291',
    messagingSenderId: '294641802180',
    projectId: 'pupdoc',
    storageBucket: 'pupdoc.firebasestorage.app',
    iosBundleId: 'com.example.pupdoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC67vvRKwO4-5RpO9p2N6iyfNGEIabzxSw',
    appId: '1:294641802180:web:b50c22a5acb72713ba2291',
    messagingSenderId: '294641802180',
    projectId: 'pupdoc',
    authDomain: 'pupdoc.firebaseapp.com',
    storageBucket: 'pupdoc.firebasestorage.app',
  );
}
